/* eslint-disable tailwindcss/classnames-order */
/* eslint-disable react/no-unknown-property */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button class="hover:font-bold border-2 rounded-md focus:scale-110">
        e
      </button>
    </div>
  )
}
